### ISSUE TITLE
I'm not familiar with GLES...  how much is it different?

### ISSUE THREAD

**Issue by cheako** [WesleyKhoiVo/GLOVE#3]
Solved: Mesa's Zink is what I was looking for.

I'm tempted to try and use `libGLESv2.so` in place of `libGL.so.1.7.0`.  I've patched up my Vulkan drivers and would even know what to do for GL.

https://gitlab.com/cheako/vk-layer-cache/-/commit/61daef318fcd9331fc9697a4f57825aac924e6e9 it's because of https://gitlab.freedesktop.org/mesa/mesa/-/issues/6012

**Comment by VOM7HC** [comment]
Thanks @cheako for contribution

But developer Think Silicon official completely removed and deleted source code GLOVE and Google ANGLE is official support GLES to Vulkan and Metal API so I think you maybe need consider move to ANGLE for better support and more API. This is unofficial mirror from Think Silicon repository, if you want, you can fork this and create your own project.
